# Site settings
title: 柒墨轩
email: 2813930556@qq.com
description: > # this means to ignore newlines until "baseurl:"
url: https://xjpmaster.github.io/qimoxuan01.github.io/ # the base hostname & protocol for your site

twitter_username:
github_username: XjpMaster



baseurl:  #https://xjpmaster.github.io/qimoxuan01.github.io/

host: 192.168.116.61 #监听网址
port: 4000 #监听端口

author: XjpMaster
authorUrl: https://xjpmaster.github.io/qimoxuan01.github.io/

permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"] #过滤这些文件


paginate: 10 #分页
paginate_path: "page:num"#分页设置

widgets:
- category
- tag
- links
- douban
- rss

# Build settings
markdown: kramdown


gems: [jekyll-paginate]
